/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_clarkson_cs_clientlib_csdp_CSDP */

#ifndef _Included_edu_clarkson_cs_clientlib_csdp_CSDP
#define _Included_edu_clarkson_cs_clientlib_csdp_CSDP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_clarkson_cs_clientlib_csdp_CSDP
 * Method:    solve
 * Signature: (Ledu/clarkson/cs/clientlib/csdp/BlockMatrix;[Ledu/clarkson/cs/clientlib/csdp/Constraint;)V
 */
JNIEXPORT void JNICALL Java_edu_clarkson_cs_clientlib_csdp_CSDP_solve
  (JNIEnv *, jobject, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
