
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 10 14:40:28 EDT 2014
//----------------------------------------------------

package edu.clarkson.cs.clientlib.caida.itdk.parser;

/** CUP generated class containing symbol constants. */
public class Syms {
  /* terminals */
  public static final int IP = 6;
  public static final int LID = 8;
  public static final int NODE = 3;
  public static final int COLON = 2;
  public static final int NODELINK = 5;
  public static final int EOF = 0;
  public static final int NID = 7;
  public static final int LINK = 4;
  public static final int error = 1;
}

