
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 01 14:50:30 EDT 2014
//----------------------------------------------------

package edu.clarkson.cs.clientlib.caida.itdk.parser;

/** CUP generated class containing symbol constants. */
public class Syms {
  /* terminals */
  public static final int ID = 5;
  public static final int NODE = 3;
  public static final int error = 1;
  public static final int COLON = 2;
  public static final int EOF = 0;
  public static final int IP = 4;
}

